# Generated by Django 5.2.6 on 2025-09-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
