# Generated by Django 5.2.6 on 2025-09-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_telefono_max_length_to_11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
