# Generated by Django 5.2.6 on 2025-10-17 00:00

from django.db import migrations

def populate_venezuela_data(apps, schema_editor):
    """
    Crea la estructura geográfica para Venezuela, Distrito Capital, Caracas.
    """
    Pais = apps.get_model('pacientes', 'Pais')
    Estado = apps.get_model('pacientes', 'Estado')
    Ciudad = apps.get_model('pacientes', 'Ciudad')

    # Crear País: Venezuela
    venezuela, created = Pais.objects.get_or_create(
        nombre='Venezuela',
        defaults={'codigo_iso': 'VE'}
    )

    # Crear Estado: Distrito Capital
    distrito_capital, created = Estado.objects.get_or_create(
        nombre='Distrito Capital',
        pais=venezuela
    )

    # Crear Ciudad: Caracas
    caracas, created = Ciudad.objects.get_or_create(
        nombre='Caracas',
        estado=distrito_capital
    )

class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20251001_2356'),
    ]

    operations = [
        migrations.RunPython(populate_venezuela_data),
    ]