# Generated by Django 5.2.6 on 2025-09-12 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Cita',
                'verbose_name_plural': 'Estados de Cita',
                'db_table': 'estados_cita',
            },
        ),
        migrations.CreateModel(
            name='MotivoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motivo de Cita',
                'verbose_name_plural': 'Motivos de Cita',
                'db_table': 'motivos_cita',
            },
        ),
        migrations.CreateModel(
            name='TipoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_estimada', models.IntegerField(blank=True, help_text='Duración estimada en minutos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cita',
                'verbose_name_plural': 'Tipos de Cita',
                'db_table': 'tipos_cita',
            },
        ),
        migrations.CreateModel(
            name='TipoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Nota',
                'verbose_name_plural': 'Tipos de Nota',
                'db_table': 'tipos_nota',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales de la cita', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.estadocita')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.motivocita')),
                ('tipo_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.tipocita')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'citas',
            },
        ),
        migrations.CreateModel(
            name='NotaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='citas.cita')),
                ('tipo_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.tiponota')),
            ],
            options={
                'verbose_name': 'Nota de Cita',
                'verbose_name_plural': 'Notas de Cita',
                'db_table': 'notas_cita',
            },
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha', 'hora_inicio'], name='citas_fecha_28c63a_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='citas_estado__36145e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('paciente', 'fecha', 'hora_inicio')},
        ),
    ]
