# Generated by Django 5.2.6 on 2025-10-12 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0001_initial'),
        ('inventario', '0001_initial'),
        ('pacientes', '0004_auto_20251001_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o notas sobre la alergia.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alergia',
                'verbose_name_plural': 'Alergias',
                'db_table': 'historiales_alergias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o notas sobre la enfermedad.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedades',
                'db_table': 'historiales_enfermedades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='historialmedico',
            options={'verbose_name': 'Historial Médico', 'verbose_name_plural': 'Historiales Médicos'},
        ),
        migrations.RemoveField(
            model_name='historialmedico',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='historialmedico',
            name='enfermedades_preexistentes',
        ),
        migrations.RemoveField(
            model_name='historialmedico',
            name='medicamentos_actuales',
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_medico', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='alergias',
            field=models.ManyToManyField(blank=True, related_name='historiales', to='historiales.alergia'),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='enfermedades_preexistentes',
            field=models.ManyToManyField(blank=True, related_name='historiales', to='historiales.enfermedad'),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='medicamentos_actuales',
            field=models.ManyToManyField(blank=True, related_name='historiales_medicamentos', to='inventario.medicamento'),
        ),
    ]
